
rag_search_space:
  rewriter:
    model_url: ["http://localhost:9000/v1"]
    #model_name: ["gpt-4o-mini"]
    #api_key: "sk-zk2f7a5868c06b406c9313170ae2852fc2a697c2f28cf9e6"
    prompt_template_id: ["1", "2", "3"]

  chunking:
    chunk_size: [256, 512, 1024, 2048]
    chunk_overlap: [0, 64, 128, 192]

  retrieve:
    model_url: ["/home/cz/ragsearch-jane/models/sentence-transformers--all-MiniLM-L6-v2", "/home/cz/ragsearch-jane/models/sentence-transformers--all-MiniLM-L12-v2"]
    topk: [1, 3, 5, 10, 20, 50]
    bm25_weight: [0.0, 0.25, 0.5, 0.75, 1.0]

  reranker:
    model_url: ["/home/cz/ragsearch-jane/models/cross-encoder--ms-marco-MiniLM-L-6-v2", "/home/cz/ragsearch-jane/models/cross-encoder--ms-marco-TinyBERT-L-2-v2"]
    topk: [1, 3, 5, 10, 20, 50]

  pruner:
    model_url: ["http://localhost:9000/v1"]
    #model_name: ["gpt-4o-mini"]
    #api_key: "sk-zk2f7a5868c06b406c9313170ae2852fc2a697c2f28cf9e6"
    prompt_template_id: ["1", "2", "3"]

  generator:
    model_url: ["http://localhost:9000/v1"]
    #model_name: ["gpt-4o-mini"]
    #api_key: "sk-zk2f7a5868c06b406c9313170ae2852fc2a697c2f28cf9e6"

eval_metrics:
  llmaaj:
    model_url: "http://localhost:9000/v1"
    #model_name: "gpt-4o-mini"
    #api_key: "sk-zk2f7a5868c06b406c9313170ae2852fc2a697c2f28cf9e6"
  bert:
    model_url: "/home/cz/ragsearch-jane/models/bert-base-uncased"
