rewriter:
  model_url: "https://api.zhizengzeng.com/v1"
  model_name: "gpt-4o-mini"
  api_key: "sk-zk2a9670ffd66cd147a52dca250662f1334694f88bae25e4"

retrieve:
  model_url:
    - "/home/cz/ragsearch-jane/models/sentence-transformers--all-MiniLM-L6-v2"
    - "/home/cz/ragsearch-jane/models/sentence-transformers--all-MiniLM-L12-v2"

reranker:
  model_url:
    - "/home/cz/ragsearch-jane/models/cross-encoder--ms-marco-MiniLM-L-6-v2"
    - "/home/cz/ragsearch-jane/models/cross-encoder--ms-marco-TinyBERT-L-2-v2"

clip:
  model_url: 
    - "/home/cz/ragsearch-jane/models/clip-ViT-B-32"

generator:
  model_url: "https://api.zhizengzeng.com/v1"
  model_name: "qwen3-vl-30b-a3b-instruct"
  api_key: "sk-zk2a9670ffd66cd147a52dca250662f1334694f88bae25e4"

eval_metrics:
  llmaaj:
    model_url: "https://api.zhizengzeng.com/v1"
    model_name: "gpt-4o-mini"
    api_key: "sk-zk2a9670ffd66cd147a52dca250662f1334694f88bae25e4"
  bert:
    model_url: "/home/cz/ragsearch-jane/models/bert-base-uncased"
