rewriter:
  model_url: "https://api.zhizengzeng.com/v1"
  model_name: "gpt-4o-mini"
  api_key: "sk-zk2f7a5868c06b406c9313170ae2852fc2a697c2f28cf9e6"

retrieve:
  model_url:
    - "/home/cz/ragsearch-jane/models/sentence-transformers--all-MiniLM-L6-v2"
    - "/home/cz/ragsearch-jane/models/sentence-transformers--all-MiniLM-L12-v2"

reranker:
  model_url:
    - "/home/cz/ragsearch-jane/models/cross-encoder--ms-marco-MiniLM-L-6-v2"
    - "/home/cz/ragsearch-jane/models/cross-encoder--ms-marco-TinyBERT-L-2-v2"

pruner:
  model_url:
    - "https://api.zhizengzeng.com/v1"
  model_name:
    - "gpt-4o-mini"
  api_key: "sk-zk2f7a5868c06b406c9313170ae2852fc2a697c2f28cf9e6"

generator:
  model_url: "https://api.zhizengzeng.com/v1"
  model_name: "gpt-4o-mini"
  api_key: "sk-zk2f7a5868c06b406c9313170ae2852fc2a697c2f28cf9e6"

eval_metrics:
  llmaaj:
    model_url: "https://api.zhizengzeng.com/v1"
    model_name: "gpt-4o-mini"
    api_key: "sk-zk2f7a5868c06b406c9313170ae2852fc2a697c2f28cf9e6"
  bert:
    model_url: "/home/cz/ragsearch-jane/models/bert-base-uncased"
